# see:
# http://relaxed.ruby.style/
# https://rubocop.readthedocs.io/en/latest/
# https://github.com/bbatsov/rubocop/blob/master/manual/cops.md
# https://github.com/bbatsov/rubocop/tree/master/config
# https://raw.githubusercontent.com/bbatsov/rubocop/master/config/enabled.yml
# https://github.com/tootsuite/mastodon/blob/master/.rubocop.yml
# https://blog.percy.io/share-rubocop-rules-across-all-of-your-repos-f3281fbd71f8
#
# Sample of use:
#
# ```yml
# inherit_gem:
#  kamaze-project:
#    - .rubocop.yml
# ```
---
AllCops: { DisplayCopNames: true, TargetRubyVersion: 2.5 }
Layout/EmptyLineAfterMagicComment: { Enabled: false }
Layout/SpaceAroundMethodCallOperator: { Enabled: true }
Lint/RaiseException: { Enabled: true }
Lint/StructNewOverride: { Enabled: true }
Lint/UnusedBlockArgument: { Enabled: false }
Metrics/AbcSize: { Max: 20 }
Metrics/ClassLength: { CountComments: false }
Metrics/CyclomaticComplexity: { Max: 10 }
Metrics/MethodLength: { CountComments: false, Max: 10 }
Metrics/ModuleLength: { CountComments: false }
Naming/MemoizedInstanceVariableName: { Enabled: false }
Style/AndOr: { Enabled: false }
Style/ClassAndModuleChildren: { Enabled: false }
Style/DoubleNegation: { Enabled: false }
Style/Encoding: { Enabled: false }
Style/ExponentialNotation: { Enabled: true, EnforcedStyle: scientific }
Style/FormatString: { Enabled: false }
Style/HashEachMethods: { Enabled: true }
Style/HashTransformKeys: { Enabled: true }
Style/HashTransformValues: { Enabled: true }
Style/IfUnlessModifier: { Enabled: false }
Style/MultilineBlockChain: { Enabled: false }
Style/RedundantReturn: { Enabled: false }
Style/RedundantSelf: { Enabled: false }
Style/Send: { Enabled: true }
Style/SymbolArray: { Enabled: false }
Style/WordArray: { Enabled: false }
Style/TrailingCommaInArrayLiteral: { Enabled: false }
Style/TrailingCommaInHashLiteral: { Enabled: false }
Style/YodaCondition: { Enabled: false }